# Generated by Django 4.2.3 on 2023-07-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_manage', '0002_remove_reviewdetails_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoteldetails',
            name='avg_rating',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
    ]
