# Generated by Django 4.2.3 on 2023-08-03 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Hotel_manage', '0004_alter_hoteldetails_avg_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoteldetails',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
